version: '3.8' 

services: 
  
  db: 
    image: postgres:latest 
    container_name: my-postgres 
    restart: always 
    environment: 
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_DATABASE}
    ports: 
      - "5433:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
  
  app: 
    build: . 
    container_name: meu_app
    restart: always
    ports:
      - "3333:3333" 
    environment: 
       DB_HOST: db
       DB_PORT: 5432
       DB_USER: ${DB_USER}
       DB_PASSWORD: ${DB_PASSWORD}
       DB_DATABASE: ${DB_DATABASE}
    depends_on: 
      - db

volumes: 
  pgdata: